/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MapRouteImport } from './routes/map'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TwinIdRouteImport } from './routes/twin.$id'
import { Route as RecommendationsIdRouteImport } from './routes/recommendations.$id'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as ApiRecommendationChatRouteImport } from './routes/api/recommendation-chat'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinIdRoute = TwinIdRouteImport.update({
  id: '/twin/$id',
  path: '/twin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsIdRoute = RecommendationsIdRouteImport.update({
  id: '/recommendations/$id',
  path: '/recommendations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecommendationChatRoute = ApiRecommendationChatRouteImport.update({
  id: '/api/recommendation-chat',
  path: '/api/recommendation-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/copilot': typeof CopilotRoute
  '/map': typeof MapRoute
  '/api/chat': typeof ApiChatRoute
  '/api/recommendation-chat': typeof ApiRecommendationChatRoute
  '/events/$id': typeof EventsIdRoute
  '/recommendations/$id': typeof RecommendationsIdRoute
  '/twin/$id': typeof TwinIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/copilot': typeof CopilotRoute
  '/map': typeof MapRoute
  '/api/chat': typeof ApiChatRoute
  '/api/recommendation-chat': typeof ApiRecommendationChatRoute
  '/events/$id': typeof EventsIdRoute
  '/recommendations/$id': typeof RecommendationsIdRoute
  '/twin/$id': typeof TwinIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clients': typeof ClientsRoute
  '/copilot': typeof CopilotRoute
  '/map': typeof MapRoute
  '/api/chat': typeof ApiChatRoute
  '/api/recommendation-chat': typeof ApiRecommendationChatRoute
  '/events/$id': typeof EventsIdRoute
  '/recommendations/$id': typeof RecommendationsIdRoute
  '/twin/$id': typeof TwinIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clients'
    | '/copilot'
    | '/map'
    | '/api/chat'
    | '/api/recommendation-chat'
    | '/events/$id'
    | '/recommendations/$id'
    | '/twin/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clients'
    | '/copilot'
    | '/map'
    | '/api/chat'
    | '/api/recommendation-chat'
    | '/events/$id'
    | '/recommendations/$id'
    | '/twin/$id'
  id:
    | '__root__'
    | '/'
    | '/clients'
    | '/copilot'
    | '/map'
    | '/api/chat'
    | '/api/recommendation-chat'
    | '/events/$id'
    | '/recommendations/$id'
    | '/twin/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientsRoute: typeof ClientsRoute
  CopilotRoute: typeof CopilotRoute
  MapRoute: typeof MapRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiRecommendationChatRoute: typeof ApiRecommendationChatRoute
  EventsIdRoute: typeof EventsIdRoute
  RecommendationsIdRoute: typeof RecommendationsIdRoute
  TwinIdRoute: typeof TwinIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin/$id': {
      id: '/twin/$id'
      path: '/twin/$id'
      fullPath: '/twin/$id'
      preLoaderRoute: typeof TwinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations/$id': {
      id: '/recommendations/$id'
      path: '/recommendations/$id'
      fullPath: '/recommendations/$id'
      preLoaderRoute: typeof RecommendationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recommendation-chat': {
      id: '/api/recommendation-chat'
      path: '/api/recommendation-chat'
      fullPath: '/api/recommendation-chat'
      preLoaderRoute: typeof ApiRecommendationChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientsRoute: ClientsRoute,
  CopilotRoute: CopilotRoute,
  MapRoute: MapRoute,
  ApiChatRoute: ApiChatRoute,
  ApiRecommendationChatRoute: ApiRecommendationChatRoute,
  EventsIdRoute: EventsIdRoute,
  RecommendationsIdRoute: RecommendationsIdRoute,
  TwinIdRoute: TwinIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
